<a href="https://colab.research.google.com/github/dior-dev-python/micro_economics/blob/main/mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [3]:
numbers = [1, 2, 3, 4, 5]
massiv = np.array(numbers)
print(massiv)

[1 2 3 4 5]


#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



In [4]:
nol_massiv = np.zeros(9)
print(nol_massiv)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


`💡Ishora` np.zeros

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [5]:
massiv = np.array([1, 2, 3, 4, 5])
memory_size = massiv.size * massiv.itemsize
print(f"Massivning xotira hajmi: {memory_size}bayt")

Massivning xotira hajmi: 40bayt


#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [7]:
vektor = np.zeros(12)
vektor[5] = 1
print(vektor)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [10]:
vektor = np.arange(20, 60)
print(vektor)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [11]:
vektor = np.arange(1, 11)
teskari_vektor = vektor[::-1]
print("Asl vektor:", vektor)
print("Teskari vektor:", teskari_vektor)


Asl vektor: [ 1  2  3  4  5  6  7  8  9 10]
Teskari vektor: [10  9  8  7  6  5  4  3  2  1]


#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [12]:
elements = np.arange(12, 21)
matrix = elements.reshape((3, 3))
print(matrix)

[[12 13 14]
 [15 16 17]
 [18 19 20]]


#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [13]:
matrix = np.array([3, 7, 0, 0, 9, 0])
non_zero_index = np.nonzero(matrix)
print("Nolga teng bolmagan elementlarning indekslari:", non_zero_index)

Nolga teng bolmagan elementlarning indekslari: (array([0, 1, 4]),)


#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [17]:
random_massiv = np.random.random((2, 2, 2))
print(random_massiv)


[[[0.873145   0.22485949]
  [0.2033229  0.41315213]]

 [[0.14449213 0.02037613]
  [0.3126621  0.95999819]]]


#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [19]:
random_massiv = np.random.rand(9, 9)
min = random_massiv.min()
max = random_massiv.max()
print("random_massiv:\n", random_massiv)
print("Eng kichik qiymat:", min)
print("Eng katta qiymat:", max)

random_massiv:
 [[0.1618915  0.09505503 0.79954368 0.59844775 0.52369652 0.4894018
  0.60139796 0.70032141 0.33979252]
 [0.43815506 0.06736618 0.8097613  0.07840529 0.81003168 0.72018053
  0.90826579 0.15216756 0.3854648 ]
 [0.6591764  0.87089079 0.80843183 0.9322854  0.25667042 0.04154275
  0.18529222 0.68250388 0.93598721]
 [0.87156097 0.11022409 0.80052374 0.37370898 0.963184   0.72752356
  0.81456533 0.75662205 0.14474427]
 [0.39682387 0.34002495 0.96270504 0.44375742 0.28818305 0.56854951
  0.28393426 0.53382044 0.25616946]
 [0.94633545 0.11585785 0.54189881 0.7592858  0.18416845 0.12918078
  0.22913354 0.46902323 0.1575091 ]
 [0.17300256 0.4245018  0.7159201  0.28014043 0.76936259 0.2313666
  0.30097622 0.51611138 0.36339093]
 [0.40168274 0.87098768 0.48434766 0.04576275 0.52663028 0.07616096
  0.07712085 0.0216396  0.90577074]
 [0.19317721 0.07978944 0.95525555 0.44152754 0.74140734 0.87487787
  0.40965274 0.39508673 0.86940597]]
Eng kichik qiymat: 0.021639597221287388
Eng katta

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [21]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

Nan
False
False
Nan
True
False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [22]:
A = np.ones((6, 3))
B = np.ones((3, 4))
C = np.dot(A, B)

print("A matritsasi:\n", A)
print("B matritsasi:\n", B)
print("A va B matritsalarining ko'paytmasi C:\n", C)

A matritsasi:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
B matritsasi:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
A va B matritsalarining ko'paytmasi C:
 [[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [23]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [24]:
a = np.array([1, 2])
b = np.array([4, 5])

print("a > b:", a > b)
print("a >= b:", a >= b)
print("a < b:", a < b)
print("a <= b:", a <= b)

a > b: [False False]
a >= b: [False False]
a < b: [ True  True]
a <= b: [ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [25]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-25-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-25-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-25-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [27]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])

overall_elements = np.intersect1d(a, b)
print("Massivlar orasidagi umumiy elementlar:", overall_elements)

Massivlar orasidagi umumiy elementlar: [4 5]


#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [28]:
massiv = np.random.uniform(-10, 10, size=5)
print("Tasodifiy sonlar:", massiv)

floor_qismi = np.floor(massiv)
print("np.floor() yordamida:", floor_qismi)

astype_qismi = massiv.astype(int)
print("astype(int) yordamida:", astype_qismi)

trunc_qismi = np.trunc(massiv)
print("np.trunc() yordamida:", trunc_qismi)

Tasodifiy sonlar: [-1.89481338  9.32227401  6.11555613  2.25753533  8.09278664]
np.floor() yordamida: [-2.  9.  6.  2.  8.]
astype(int) yordamida: [-1  9  6  2  8]
np.trunc() yordamida: [-1.  9.  6.  2.  8.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [29]:
matrix = np.tile(np.arange(3), (3, 1))
print(matrix)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [30]:
random_vektor = np.random.rand(10)
print("Tasodifiy vektor:", random_vektor)

sorted_vektor = np.sort(random_vektor)
print("O`sish tartibida:", sorted_vektor)

Tasodifiy vektor: [0.82060601 0.74924042 0.07168476 0.39242429 0.83832829 0.63467972
 0.92415316 0.28636699 0.08119157 0.90467242]
O`sish tartibida: [0.07168476 0.08119157 0.28636699 0.39242429 0.63467972 0.74924042
 0.82060601 0.83832829 0.90467242 0.92415316]


#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [31]:
A = np.random.rand(5)
B = np.random.rand(5)
print("A massivi:", A)
print("B massivi:", B)

allclose_tekshiruv = np.allclose(A, B)
print("A va B massivlari np.allclose() bilan solishtirganda:", allclose_tekshiruv)

array_equal_tekshiruv = np.array_equal(A, B)
print("A va B massivlari np.array_equal() bilan solishtirganda:", array_equal_tekshiruv)

A massivi: [0.80242794 0.8541054  0.72089209 0.13001393 0.30309723]
B massivi: [0.98721204 0.05255401 0.04862631 0.54344701 0.81268644]
A va B massivlari np.allclose() bilan solishtirganda: False
A va B massivlari np.array_equal() bilan solishtirganda: False


#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [32]:
A = np.ones((6, 3))
B = np.ones((3, 4))
C = np.dot(A, B)

print("A matritsasi:\n", A)
print("B matritsasi:\n", B)
print("A va B matritsalarining ko'paytmasi C:\n", C)


A matritsasi:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
B matritsasi:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
A va B matritsalarining ko'paytmasi C:
 [[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [33]:
vektor = np.random.rand(5)
print("Tasodifiy vektor:", vektor)

max_index = np.argmax(vektor)

vektor[max_index] = 0

print("Yangilangan vektor:", vektor)

Tasodifiy vektor: [0.16369016 0.07825272 0.62263125 0.75508822 0.38753066]
Yangilangan vektor: [0.16369016 0.07825272 0.62263125 0.         0.38753066]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [34]:
bugun = np.datetime64('today', 'D')

kecha = bugun - np.timedelta64(1, 'D')

ertaga = bugun + np.timedelta64(1, 'D')

print("Kecha:", kecha)
print("Bugun:", bugun)
print("Ertaga:", ertaga)

Kecha: 2024-11-08
Bugun: 2024-11-09
Ertaga: 2024-11-10


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [35]:
yanvar_kunlari = np.arange('2016-01-01', '2016-02-01', dtype='datetime64[D]')

print("2016 yil yanvar oyiga to'g'ri keladigan kunlar:")
print(yanvar_kunlari)

2016 yil yanvar oyiga to'g'ri keladigan kunlar:
['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [36]:
massiv = np.random.uniform(0, 10, 5)
print("Tasodifiy massiv:", massiv)

astype_qismi = massiv.astype(int)
print("astype(int) yordamida:", astype_qismi)

trunc_qismi = np.trunc(massiv)
print("np.trunc() yordamida:", trunc_qismi)

modulus_qismi = massiv - (massiv % 1)
print("Modulus operatori % yordamida:", modulus_qismi)

Tasodifiy massiv: [1.65508755 4.86564303 9.22096072 4.6862876  3.58601758]
astype(int) yordamida: [1 4 9 4 3]
np.trunc() yordamida: [1. 4. 9. 4. 3.]
Modulus operatori % yordamida: [1. 4. 9. 4. 3.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [37]:
massiv1 = np.array([1, 2, 3])
massiv2 = np.array([4, 5, 6])

yigindi = np.add.reduce(np.add(massiv1, massiv2))
print("Massivlar yig'indisi:", yigindi)

Massivlar yig'indisi: 21


#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [38]:
original_vector = np.array([1, 2, 3, 4, 5])

nollarning_soni = (len(original_vector) - 1) * 3

yangi_olcham = len(original_vector) + nollarning_soni

new_vector = np.zeros(yangi_olcham, dtype=int)

new_vector[np.arange(len(original_vector)) * 4] = original_vector

print("Yangi massiv:", new_vector)

Yangi massiv: [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [39]:
from numpy.lib.stride_tricks import as_strided

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

window_length = 4
n_windows = len(a) - window_length + 1

b = as_strided(a, shape=(n_windows, window_length), strides=a.strides * 2)

print("b massivi:")
print(b)


b massivi:
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [41]:
a = np.random.randint(1, 10, size=20)
print("Original massiv:", a)

count = np.bincount(a)

most_frequent = np.argmax(count)

print("Eng ko'p uchragan qiymat:", most_frequent)
print("Uning takrorlanish soni:", count[most_frequent])

Original massiv: [7 4 9 4 3 4 7 4 4 9 5 8 8 3 8 2 2 9 7 6]
Eng ko'p uchragan qiymat: 4
Uning takrorlanish soni: 5


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`